# Generated by Django 5.2.6 on 2025-09-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Access Role Name')),
                ('status', models.CharField(default='active', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Role',
                'verbose_name_plural': 'Access Roles',
                'ordering': ['created_at'],
            },
        ),
    ]
