# Generated by Django 5.2.6 on 2025-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Location Name')),
                ('upload_path', models.CharField(blank=True, max_length=512, null=True)),
                ('print_path', models.CharField(blank=True, max_length=512, null=True)),
                ('download_path', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(default='1', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['created_at'],
            },
        ),
    ]
