# Generated by Django 5.2.6 on 2025-09-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessrole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255, unique=True, verbose_name='Page Name')),
                ('module_name', models.CharField(max_length=255, verbose_name='Module Name')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page List',
                'verbose_name_plural': 'Page Lists',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Assignrole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('view', models.BooleanField(default=False, help_text='Permission to view this page.')),
                ('insert', models.BooleanField(default=False, help_text='Permission to add new data.')),
                ('update', models.BooleanField(default=False, help_text='Permission to update existing data.')),
                ('delete', models.BooleanField(default=False, help_text='Permission to delete data.')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to='accessrole.accessrole')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pages', to='assignrole.pagelist')),
            ],
            options={
                'verbose_name': 'Assigned Role',
                'verbose_name_plural': 'Assigned Roles',
                'ordering': ['-date'],
            },
        ),
    ]
