# Generated by Django 5.2.6 on 2025-09-22 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateBarcodeException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('duplicate_barcode', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Duplicate_location', to='location.location')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingLabelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='pdfs/')),
                ('status', models.IntegerField(default=0)),
                ('print_download_status', models.IntegerField(choices=[(0, 'New / Unprinted'), (1, 'Printed / Successfully Processed'), (2, 'Sent for Printing')], default=1, verbose_name='Print Status')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_location', to='location.location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScannedBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_value', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('shipping_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='barcode_app.shippinglabeldata')),
            ],
        ),
    ]
