# Generated by Django 5.2.6 on 2025-09-22 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatebarcodeexception',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scannedbarcode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcodes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippinglabeldata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippinglabeldata',
            name='updated_by',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
